services:
  postgres:
    image: postgres:16-alpine
    container_name: nodebuy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nodebuy
      POSTGRES_PASSWORD: nodebuy
      POSTGRES_DB: nodebuy
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
