/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    providers: Provider;
    plans: Plan;
    reviews: Review;
    rankings: Ranking;
    deals: Deal;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    rankings: RankingsSelect<false> | RankingsSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: number;
  name: string;
  slug: string;
  tagline?: string | null;
  description?: string | null;
  website?: string | null;
  /**
   * /go/<slug> 将 302 跳转到此链接
   */
  affUrl?: string | null;
  logo?: (number | null) | Media;
  /**
   * 无 Logo 时用于生成字母徽标底色
   */
  brandColor?: string | null;
  founded?: number | null;
  headquarters?: string | null;
  paymentMethods?: ('alipay' | 'wechat' | 'paypal' | 'card' | 'crypto' | 'unionpay')[] | null;
  datacenters?:
    | {
        city: string;
        region?: ('na' | 'eu' | 'apac' | 'cn') | null;
        cnOptimized?: boolean | null;
        id?: string | null;
      }[]
    | null;
  scores?: {
    performance?: number | null;
    network?: number | null;
    value?: number | null;
    support?: number | null;
  };
  overallScore?: number | null;
  pros?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  cons?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  name: string;
  provider: number | Provider;
  cpuCores: number;
  ramMB: number;
  storageGB: number;
  storageType?: ('nvme' | 'ssd' | 'hdd') | null;
  /**
   * 0 表示不限
   */
  trafficTB?: number | null;
  bandwidthMbps?: number | null;
  location?: string | null;
  priceMonthly?: number | null;
  priceYearly?: number | null;
  route?: ('cn2gia' | 'cn2gt' | 'cmin2' | '9929' | '4837' | 'direct' | 'bgp') | null;
  highlight?: string | null;
  affUrl?: string | null;
  inStock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  title: string;
  slug: string;
  provider: number | Provider;
  plan?: (number | null) | Plan;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt: string;
  author?: string | null;
  readingMinutes?: number | null;
  scores?: {
    performance?: number | null;
    network?: number | null;
    value?: number | null;
    support?: number | null;
  };
  verdict?: string | null;
  benchmarks?: {
    cpuModel?: string | null;
    gb5Single?: number | null;
    gb5Multi?: number | null;
    diskReadMBs?: number | null;
    diskWriteMBs?: number | null;
    speedtests?:
      | {
          node: string;
          downloadMbps?: number | null;
          uploadMbps?: number | null;
          latencyMs?: number | null;
          id?: string | null;
        }[]
      | null;
    routes?:
      | {
          isp?: ('ct' | 'cu' | 'cm') | null;
          path: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rankings".
 */
export interface Ranking {
  id: number;
  title: string;
  slug: string;
  category: 'overall' | 'value' | 'cn-optimized' | 'performance' | 'storage' | 'budget';
  description?: string | null;
  methodology?: string | null;
  featured?: boolean | null;
  items?:
    | {
        provider: number | Provider;
        plan?: (number | null) | Plan;
        score?: number | null;
        summary?: string | null;
        bestFor?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  title: string;
  provider: number | Provider;
  description?: string | null;
  code?: string | null;
  discount?: string | null;
  expiresAt?: string | null;
  url?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'providers';
        value: number | Provider;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'rankings';
        value: number | Ranking;
      } | null)
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  website?: T;
  affUrl?: T;
  logo?: T;
  brandColor?: T;
  founded?: T;
  headquarters?: T;
  paymentMethods?: T;
  datacenters?:
    | T
    | {
        city?: T;
        region?: T;
        cnOptimized?: T;
        id?: T;
      };
  scores?:
    | T
    | {
        performance?: T;
        network?: T;
        value?: T;
        support?: T;
      };
  overallScore?: T;
  pros?:
    | T
    | {
        item?: T;
        id?: T;
      };
  cons?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  provider?: T;
  cpuCores?: T;
  ramMB?: T;
  storageGB?: T;
  storageType?: T;
  trafficTB?: T;
  bandwidthMbps?: T;
  location?: T;
  priceMonthly?: T;
  priceYearly?: T;
  route?: T;
  highlight?: T;
  affUrl?: T;
  inStock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  provider?: T;
  plan?: T;
  excerpt?: T;
  content?: T;
  publishedAt?: T;
  author?: T;
  readingMinutes?: T;
  scores?:
    | T
    | {
        performance?: T;
        network?: T;
        value?: T;
        support?: T;
      };
  verdict?: T;
  benchmarks?:
    | T
    | {
        cpuModel?: T;
        gb5Single?: T;
        gb5Multi?: T;
        diskReadMBs?: T;
        diskWriteMBs?: T;
        speedtests?:
          | T
          | {
              node?: T;
              downloadMbps?: T;
              uploadMbps?: T;
              latencyMs?: T;
              id?: T;
            };
        routes?:
          | T
          | {
              isp?: T;
              path?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rankings_select".
 */
export interface RankingsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  description?: T;
  methodology?: T;
  featured?: T;
  items?:
    | T
    | {
        provider?: T;
        plan?: T;
        score?: T;
        summary?: T;
        bestFor?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  provider?: T;
  description?: T;
  code?: T;
  discount?: T;
  expiresAt?: T;
  url?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}